kname: application_heety_client
description: Heety Client Application

version: 1.1.0+23

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^4.17.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_google_places_sdk: ^0.3.9
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  flutter_stripe: ^10.1.1
  flutter_styled_toast: ^2.2.1
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  geocoding: ^2.2.2
  geolocator: ^10.1.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  google_maps_cluster_manager:
    git:
      url: https://github.com/MacDeveloper1/google_maps_cluster_manager.git
      ref: fix/cluster
  google_maps_flutter: ^2.6.1
  group_button: ^5.3.4
  heety_tools:
    path: packages/heety-tools
  http: ^1.2.1
  intl: ^0.19.0
  local_auth: ^2.2.0
  logging: ^1.2.0
  mime: ^1.0.5
  modal_bottom_sheet: ^3.0.0
  omni_datetime_picker: ^1.1.0
  open_file: ^3.3.2
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf_render: ^1.4.7
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  upgrader: ^10.3.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.7
  test: ^1.24.9
  analyzer: ^6.2.0
  very_good_analysis: ^5.1.0
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_gen:
  line_length: 80
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#67A9AA"
  image: assets/images/splash.png
  android_12:
    image: assets/icons/ic_foreground.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/ic_foreground.png"
  adaptive_icon_monochrome: "assets/icons/ic_logo_monochrome.png"
  image_path: "assets/icons/ic_logo_rectangle.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/ic_logo_round.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map/
    - assets/images/
    - assets/logos/
    - assets/icons/

scripts:
  ios: open -a Simulator;
  android: flutter emulators --launch $(flutter emulators | grep '• android' | cut -d' ' -f1);
  test: very_good test --coverage;
  configure:
    flutter pub get;
    dart run flutter_launcher_icons:main;
    dart run flutter_flavorizr;
    dart run flutter_native_splash:create;
    cp -v ios/Runner/Base.lproj/LaunchScreen.storyboard ios/Runner/stagingLaunchScreen.storyboard;
    cp -v ios/Runner/Base.lproj/LaunchScreen.storyboard ios/Runner/productionLaunchScreen.storyboard;
    cp -v ios/Runner/Base.lproj/LaunchScreen.storyboard ios/Runner/developmentLaunchScreen.storyboard;
  refresh:
    flutter pub get;
    dart run build_runner clean;
    dart run build_runner build --delete-conflicting-outputs;
    dart fix --apply;
    dart format lib/;

