name: Deploy Flutter App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        git-token: ${{ secrets.ACTIONS_TOKEN }}

    - name: Increment version
      run: ./increment_version.sh

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}

